### ISSUE TITLE
[Bug] Copyright-claimed videos are unsupported

### ISSUE THREAD

**Issue by VelvetToroyashi** [kuylar/LightTube#79]
### Describe the bug

When using LightTube, there is an expectation (given the lack of indication otherwise) that viewing access is generally unrestricted when using LightTube as a YouTube frontend, perhaps barring NSFW content. 

In the midst of showing LightTube to someone as an alternative to YouTube's frontend, and especially their insistence on blocking copyrighted content in embedded media, such as Discord Embeds, I stumbled upon an issue wherein LightTube simply displays that 'The media could not be loaded, either because the server or network failed or because the format is not supported.', which is a generic and unhelpful error, as well as being incorrect for the situation.

This can be observed when loading anything that wouldn't play in Discord, typically music. For example, [this song](https://tube.kuylar.dev/watch?v=u2PHgCuuX1A). 

### Notes

I don't touch YouTube's APIs, so I'm not sure if or how this would be fixed, but wanted to raise attention to the issue. In the event that this an unavoidable issue (you've gotten this far, I'm sure this is a piece of cake for you Kuylar), I would at least acknowledge/address this as a known issue with LightTube, and not something that can be fixed in the readme.

**Comment by kuylar** [comment]
> 'The media could not be loaded, either because the server or network failed or because the format is not supported.', which is a generic and unhelpful error, as well as being incorrect for the situation.

The error message comes from Video.JS - which has caused a lot more problems in the past 

The reason copyrighted media returns that error is because they are IP-locked, meaning only the instance can download/stream the file, and everyone else gets an HTTP 403

This is where the video proxy comes into play. It's possible that the instance you were using had the proxy disabled via the `LIGHTTUBE_DISABLE_PROXY` environment variable, which meant that the IP of the device that initiated the video playback differed from the IP of the device which wanted to play, and YouTube just said "yeah no"

> Barring NSFW content

YouTube has a *very* strict NSFW check, and there are 2 ways of bypassing it. The first way is to find a client name/version pair that doesn't have age-checking, which can break at any time soon, so we don't do that

The second way is to just make authenticated requests only to the `/player` endpoint to get the video, which also has to be enabled by the instance host

So, if I understood everything correctly, this seems to be a small configuration problem. I'm gonna keep this issue open if that's not the case

**Comment by VelvetToroyashi** [comment]
Well this also happens on your (or, the "official" if you want to call it that) instance, and I'd assume your instance is set up to be rather permissive. I don't know the requirements/setup for running an instance, so I can't test it myself at the moment, but you can click the link I posted to see for yourself as well

**Comment by kuylar** [comment]
![image](https://github.com/kuylar/LightTube/assets/52961639/9b842a01-a418-44ef-a465-5b90b16111cb)
![image](https://github.com/kuylar/LightTube/assets/52961639/19de3ad6-dfca-482a-9720-19f236d3c040)

**Comment by VelvetToroyashi** [comment]
(Worth noting this was fixed after @kuylar purged an old instance off her server, so, appears to be fixed I suppose?)

**Comment by kuylar** [comment]
(the issue was related to kuylar/InnerTube#31 and had nothing to do with copyrighted videos because every video was broken)
